### ISSUE TITLE
FlappyBird Version, License and README.md

### ISSUE THREAD

**Issue by nemysis** [stronglink/FlappyBird#26]
Please add some usefull in README.md, not only
![Alt text](http://i.imgur.com/CVAJc7b.png)

And which are Version and License? Please add these in Sources.

Then I can make FreeBSD Port and openSUSE RPM.
Thanks

**Comment by stronglink** [comment]
Added some usage details to the README. I'll hold off on the versioning and license for now (as they are not relevant).
